### ISSUE TITLE
Version 3 Design Proposal

### ISSUE THREAD

**Issue by rlove** [utPLSQL/utPLSQL#10]
I took a couple of days thinking of how I might write version 3.    It turned into something way bigger than in had planned.   

Since it involves lots of files, I put it in a new repository as I thought it might be easier to communicate.

https://github.com/rlove/ut3

**Comment by DDieterich** [comment]
Well, it looks like I am late to the party.  I also have a running prototype for v3, but I haven't figured out enough GitHub to upload it.  I took a different approach.  I zipped what I have and attached it here.  Still smoothing the rough edges...
[core-2016-02-24.zip](https://github.com/utPLSQL/utPLSQL/files/145722/core-2016-02-24.zip)

**Comment by PaulWalkerUK** [comment]
I'll be honest, I don't know how best to do this...

You two have both put a significant amount of time and effort into these. I haven't looked at them closely enough to see if the approaches share any common ground.

My position is perhaps a little unusual in that I've only used utPLSQL in a handful of small projects and about 18 months ago, I changed roles so now I *never* get the opportunity to actually use it! I'm conscious that pretty much anyone interested enough to contribute to the project (code, discussions, etc) will have more experience with it and are using it more than I do.

I think we're all agreed the code needs a good tidy up and it's time to drop support for old versions of Oracle (I don't know what the minimum version should be). In terms of a major redesign, I haven't been particularly pushing for that because to be perfectly honest, I doubt I'll have much time to make significant contributions in that area (designing or coding). I was initially thinking v3 could basically just be a rigorous clean up, taking more of an iterative approach. However, it seems there are people who are actually using it who like the idea of a major redesign so I don't want to get in the way of that. 

I can offer my opinions and try to mediate things, but I think it's going to come down to people like yourselves (who have experience with it and are enthusiastic enough to be contributing) to try to drive out the design.

What's the best way to progress this? Is there anything in particular I can do to help? If you need anything like extra repositories on here or you want me setup anything to make the conversations/collaboration easier (see #7 and #9), please let me know.

I'm also relatively new GitHub, so I don't know the best way to do things on here yet either...

**Comment by rlove** [comment]
@DDieterich looks like you have spent a great deal of time working on your design.   It's going to take me some time to look at it in depth.    I can see we have different ideas on how to do things.    I suspect we both had our own internal problems we were trying to solve.   I have only spent 2 days on my code and it was done to communicate my ideas more than anything.    

I think it might be wise to by start collecting a list of features of each.    That way we can decide which features we ultimately want in the final v3 product.

**Comment by DDieterich** [comment]
Still learning Github.  So, I thought I would drop my feature list here:

New Features
- Split functionality into core and add-ons.
- Move legacy (v2) functionality into an add-on.
- Include code coverage in core.
- Functional ad-hoc assertion (outside of Test Suite).
- Simplified repository
- Defined upgrade path from latest v2
- PL/SQL driven testing only.
- Unit testing non-package objects like table triggers

Features being removed
- No required “prefixes” on names
- No required setup or teardown procedures
- No pre­setup of TestSuite/TestCase configuration
- No broad support for ancient Oracle database versions
- No single step installation (Simplicity over convenience)

**Comment by Shoelace** [comment]
I agree with all of the "new features" listed in @DDieterich 's post above.
as for the removed features.. i assume you mean by "no required ...." you mean "are now optional" ?  in which case i would agree with them also..


I used to be of the opinion that the unit test should reside in the same package as the code itself but I am slowly disfavoring that approach , mainly because it requires you to have utplsql installed in each environment..however i think it should still be supported.

Otherwise I have had a bit of look over both sets of code and have the following comments and ideas. (_please correct me if i am wrong on any of these points_)

1. i really like the addition of code coverage in @DDieterich 's code.. but instead of installing the plsql_profiler_xxx tables maybe it should be conditional on if the user has access

2. neither set of code seem to easily support the concept of a multiple test procedures. 

ie i have often have setup my tests up like

```plsql
create or replace package ut_david 
as
    PROCEDURE ut_setup;
    PROCEDURE ut_teardown;

    PROCEDURE ut_david_1;
    PROCEDURE ut_david_2;
    PROCEDURE ut_david_3;
end ut_david;
```

and rely on UT to run them in order automatically.. and all i have to supply is the package schema.name (NB: i did submit a patch to the original code that enabled this ordering )

3. i prefer @rlove 's style of package types and then supporting multiple output providers
but the setup required in the exampel "ut3RunExampleTestSuite.sql" seems tedious. surely a lot of that could be automated/streamlined with predefined variable names in the test package spec

ie
```plsql
create or replace package ut_exampletest
AS
-- UTPLSQL declarations
ut_setup varchar2(100) := 'setup';
ut_teardown varchar2(100) := ''; --null means not required

--optional
ut_testprefix varchar2(100) := 'ut_'; -- if null/not specified then all (0 argument) procedures that are not setup/teardown are run in alphanumberic order.

--alternative
ut_testset ut3Types.TestList :=
(/* define each test in the required order here */ );


--- ---
-- public test declarations below

 procedure Setup;
 procedure ut_exampletest_1;
 procedure ut_exampletest_2;
 procedure this_would_not_get_run;
 function neither_would_this(x number) return number;

--alternative naming scheme
   PROCEDURE ut_000_create;
   PROCEDURE ut_001_right_aligned;
   PROCEDURE ut_002_left_aligned;

END;
```

the goal i want to get to is to be able to just go ``` exec utplsql.executetestset(USER,'ut_exampletest');```  or equivalent which might be closer to
```exec ut3TestRunner.ExecuteTests(NULL, USER,'ut_exampletest') -- null suite```

ie.. i would like the test package to be self contained and you just point utplsql at it.  and then layer test suites/aggregation on top of that

4. i would prefer if all 'assert' functions were in a single package.. but i understand the rationale behind putting say dbms_pipe asserts in a separate package.

5.there was mention made of utl_call_stack package from 12c.. i wrote an api compatible backport based dbms_utility.format_stack_trace that works for at least 11gr2 that can be dropped in if required


Other points/ideas:
* i like the "load scripts from oracle directory" feature. (even if i dont use it)
* being able to simply compare oracle object_type or plsql record types would be cool (with themselves.. not each other)
* maybe some sort of automated flashback control
* still want to support single installation with multiple users
* output option to sql*developer unit test result tables / other integration somehow.
* im not worried about licencing/relicensing.. would anyone release a product that use utplsql as part of them (which would then necessitate GPLing the entire program) ?  as opposed to just using to for its testing / during development..  its a tool for use during development.. its not included in deployed  products.  but im not against it either.


well thats my 4.5cents worth .. i'll post more if i think of anything..

**Comment by rlove** [comment]
@DDieterich  That is a great list of features.     I noticed in your code you mention SOLID.  SOLID is for object-oriented design.   The principles are sound and good.    However we are bound to procedural PL/SQL.  So sometimes trade-offs and workarounds have to be found.   I looked at doing my code with Object Types and they lack so many features I gave up.   
The (Pluto-Test-Framework)[https://github.com/rlove/pluto-test-framework] Project does it with object types.    

Ultimately I took the following design ideas an principles when coding my proposal.

1.  Each Package has a single focus area.  ("S"OLID)   It should not do too much.   
2.  Dependancies where possible should be passed in. (SOLI"D") Example:  Don't select from the db if it can be passed in from another package.   
3.  Interfaces can be developed with a implied contract that  a  package will have a given set of methods that have the correct parameters.    "Tests", "Reporters" use this concept.  (SO"L"ID)
4.  Interface should be be developed as needed, and be as specific as needed instead of having a single type that defines all dynamic code.  Currently I have "tests" and "reporters", and like your concept. (SOL"I"D)
4.  Security must be reviewed all the time.     For example EXECUTE IMEDIATE is a potential SQL injection security hole, validate everything before putting it in the Dynamic SQL statement.
5.  Avoid PackageA referencing PackageB, and PackageB referencing PackageA.   I maintain code like this and it's a nightmare of spaghetti.  I have found have a "types" package is critical reducing the possibility of this.   Also when this occurs you typically have not followed ("S"OLID)
6.  DMBS_Output should only occur when user of the system asks for it.  
7.  Our code should not impact the code that is being tested.  So avoid Commit or Rollback.
8.  Tests should not silently fail to run.  (v2 currently can happen if test packages are invalid)


Since there is no inheritance i can't see out the Open-Close principal could be applied (S"O"LID)

@Shoelace 
I agree that it's tedious to setup suites.   That is why I thought it would be wise to have suite manager.    That was because of principle #2 above.  That API is would hopefully be consumed by a suite management package and most of it automated.       I 

I like the concept of having a test having "test metadata"  that can control the default behaviors.     I think I will have write a simple package manager using that concept as demonstration.   

The concept of custom reporters would allow for reporting other tables, and potentially sql*devloper tables.    

My concern on licensing is not with our products, it's with PL/SQL Development IDES hopefully being able to use our code.

**Comment by DDieterich** [comment]
@PaulWalkerUK said,

> it's time to drop support for old versions of Oracle (I don't know what the minimum version should be) 

Current releases of utPLSQL should support the oldest available database version from Oracle.  That would limit current functionality to Oracle XE 11gR2.  Any testing of features beyond those capabilities would/could be available in "add-ons".

**Comment by DDieterich** [comment]
@Shoelace said,

> as for the removed features.. i assume you mean by "no required ...." you mean "are now optional" ? in which case i would agree with them also..

Optional yes, but let me address each item:

- **No required “prefixes” on names** - can optionally be defined.  Will limit test cases to those with the prefix.
- **No required setup or teardown procedures** - can be used if prefixes are defined.  My example does not have this yet.  It is next on my list for my prototype.  This would also bring back the "per method setup" parameter.
- **No pre­setup of TestSuite/TestCase configuration** - This would only be an option in an add-on.  The core would not have provisions for any kind of presetup.  All core configuration is done in the PL/SQL package that drives each TestSuite, or as a utplsql.run procedure parameter.

**Comment by DDieterich** [comment]
@Shoelace said,

> but instead of installing the plsql_profiler_xxx tables maybe it should be conditional on if the user has access

I struggled with this in my prototype.  This is why I resolved it the way I did.

- Optional tables are difficult to support without some form of dynamic SQL.
- These tables are temporary tables that are cleaned while they are used.
- These tables include comments.

And besides, why would we want code coverage to be optional?

**Comment by DDieterich** [comment]
@Shoelace said,

> neither set of code seem to easily support the concept of a multiple test procedures.

My apologies for the confusion.  I have targeted my prototype to run this code:

```
create or replace package ut_david 
as
    PROCEDURE ut_setup;
    PROCEDURE ut_teardown;

    PROCEDURE ut_david_1;
    PROCEDURE ut_david_2;
    PROCEDURE ut_david_3;
end ut_david;
```
I only have excuses for why it won't run that code now.  Interestingly, because a DOUT (Database Object Under Test) is not specified, that code won't have any code coverage.

**Comment by Shoelace** [comment]
> Current releases of utPLSQL should support the oldest available database version from Oracle. That would limit current functionality to Oracle XE 11gR2. Any testing of features beyond those capabilities would/could be available in "add-ons".

11g seems like a reasonable target.. and as been said before.. you can always use teh current version for earlier database version if required.

> I struggled with this in my prototype. This is why I resolved it the way I did.
* Optional tables are difficult to support without some form of dynamic SQL.

true.. if no access is available then it either needs to be hidden via
* conditional compilation
* dynamic sql ( execute immediate )
or
* in a separate package that is only called if its valid.  (ie check metadata status = VALID .. seen this style once)

> And besides, why would we want code coverage to be optional?

i guess i was more concerned about the versioning of these table to match the underlying dbms_profiler package/ db version..  do you know if the definitions are the same in 11g and 12c ?

~~is there any advantage to use DBMS_HPROF over DBMS_PROFILER  ?~~
never mind  dbms_hprof requires file directory access

**Comment by DDieterich** [comment]
@Shoelace 

> i guess i was more concerned about the versioning of these table to match the underlying dbms_profiler package/ db version.. do you know if the definitions are the same in 11g and 12c

Indeed!  Another struggle with the implementation.  My thinking is this is closely related to how utPLSQL v3 will support different versions of Oracle.  Even if 11g and 12c are the same, the issue needs to be addressed.  My short-term decision was to deliver a default (lowest level) definition, then have the installer overwrite with a newer definition, if needed.  This is especially useful when considering the installer may need to overwrite other portions of utPLSQL to use the newer definition.

**Comment by DDieterich** [comment]
@rlove 

> I noticed in your code you mention SOLID. SOLID is for object-oriented design. The principles are sound and good. However we are bound to procedural PL/SQL.

Many thanks for addressing these principles and adding your list.

**Comment by jgebal** [comment]
Hi guys,
It looks like since a move to github, suddenly the project got a lot of interest.
I'd like to add few pennies to it as I'm using utplsql for a year or so with previous experiences using ruby-plsql and ruby-plsql-spec.

I also recently read heard and talked a lot about TDD and Unit Testing in general, trying to make more and more database developers "test-infected".

The current layout and asumptions of utPlsql (v2) cause lot of trouble when trying to implement good TDD and Unit Testing practices.
My main pain points from v2 were:
- mandatory setup/teardown 
- not enough assertions (just equity)
- not enough assertions (data-types)
- tests not running when tested code not compiling (ghost tests)
- tests reporting utplsql exception stack and covering code exception stack
- no assertions for object types
- naming assertions not tests
- suggested approach of one test per one tested unit of code
- lack of not_raises assertion
- trouble with using dynamic-sql assertions (like throws) when working with object/collection type parameters
- terrible default formatting - too verbose and too noisy
- format of report connected with output (screen/file), so HTML can only go to DB sever filesystem.
- lack of formatting like XML/Json/JUnit
- lack of code coverage reporting
- lack of timings per test execution -> no idea which tests are slowest
- utplsql fails when assertions like: `utassert.eq('whatever', 1, 1)` would change into `utassert.eq('whatever', 1, '1')`

With v3 I have faith to get those resolved.

It's a huge challenge and to build a good testing framework with PLSQL and I'd love to contribute. Though I'm short on time, I have few ideas.
Currently I'm working on something that would allow easy assertions and comparison on any object and maybe in future compare cursor(s) with objects or JSON-like text or CSV text.

Having tests named instead of assertions would allow nice usage of nested tests and suites (using PLSCOPE). So with code like:
```plsql
procedure my_substr_fails_on_null_start is
begin
  utassert.test( 'raises exception when null p_start passed' );
  utassert.raises(q'[my_substr('test',null,10)]',-20001);
end;
procedure my_substr_tests is
begin
  utassert.test( 'MY_SUBSTR' );
  my_substr_fails_on_null_start;
end;
```
we could have nice hierarchical output:
```
MY_SUBSTR
  raises exception when null p_start passed
```
This would also open doors for great reuse of tests. We could also nicely name setup or use BDD GIVEN/WHEN/THEN syntax in descriptions.
I currently mimic this with code like:
```
utassert.this('given: customer ordered 10 items', 1 = 1)
```

**Comment by jgebal** [comment]
Some great presentations about TDD and Unit testing that could also help us define what is missing in the framework:
[Ian Cooper - TDD, where did it all go wrong - Interview](https://www.youtube.com/watch?v=HNjlJpuA5kQ)
[Ian Cooper - TDD, where did it all go wrong - Talk](http://www.infoq.com/presentations/tdd-original)
[Kevlin Henney - What We Talk About When We Talk About Unit Testing - Talk](http://www.infoq.com/presentations/unit-testing-tips-tricks)

Even though they come from OO world, they are abstract enough to fit into PLSQL as generic rules.

**Comment by DDieterich** [comment]
@jgebal 

I read through your list and agree with you on many points.  Do you want these items added to the [Wiki version-3](https://github.com/utPLSQL/utPLSQL/wiki/version-3) page?

> format of report connected with output (screen/file), so HTML can only go to DB sever filesystem.

That is interesting.  Instead of running something like "execute utplsql.run('MyTestPackage')" you could send a URI to the database like "http://127.0.0.1/pls/utplsql_run?package_name_in=MyTestPackage" and get back a web page of unit test results.

> lack of formatting like XML/Json/JUnit

I will be glad to write a JUnit XML report for Jenkins.  I have done one for SQL*Developer and one for the current utPLSQL.

**Comment by DDieterich** [comment]
I have "rounded the edges" on the prototype I created.  I tested it on a Windows/XE11gR2 install.  Most of the documentation is up-to-date.  It includes a quick install and a working example of the "betwnstr" unit test.  (No implied warantee, use at you own risk, offer not valid in certain states, etc...)

[utPLSQLv3Core2.zip](https://github.com/utPLSQL/utPLSQL/files/149764/utPLSQLv3Core2.zip)

As I told Paul, this is throw-away code if it is not the desired direction for v3.

The ZIP includes an incomplete document "utPLSQLv3Proposal" (ODT and PDF) that is a work-in-progress.  I have started converting this content to wiki pages.  Much of this is basic objectives, gap, and transition analysis.

**Comment by rlove** [comment]
I have been looking at @DDieterich code base.   It looks good, it's a very different direction than my code.   I feel new to the community and don't want to step on any toes.      But having two code bases and two directions will be counter productive.    

But here is my Suggested direction:

1. Create v3 Branch
2. Put @DDieterich code in that branch.
   - It's **clean code** which will be easy to work from.  (Something v2 was not)
   - It has an upgrade path (something mine does not have)
3. Refactor v3 code to implement many of my design principles as I believe it will make it easier to unit test many parts of our own code base.
4. Implement many of the others features requests/ideas.

@DDieterich and others are you OK with this idea?   If so do you feel you can figure out GIT to create or Pull Request or do you want me do do it with your code?

**Comment by jgebal** [comment]
There is so much typing that it would be better to talk.
All use Google hangouts?
We can safely meet on appear.in temporary conf room - no mails and sign in
required.
We can also have permanent (closed) conf room and a slack project channel
for non public discussions.

**Comment by rlove** [comment]
I have used hangouts many times and would be willing to participate with something if I scheduling works out.

**Comment by DDieterich** [comment]
@rlove 
I am good with everything, especially refactoring.  My intention was to seed the iteration process.  V2 just didn't seem to be a good starting point.  Also, it would be faster for you to start the Pull Request.  I will catch-up, I promise.

@jgebal
I am on Google, but I am not able to schedule anything during the week.  Select Saturdays are my set-aside to work on this project.  My next Saturday will be 19-March.

**Comment by rlove** [comment]
@PaulWalkerUK  I am unable to submit a pull request for version 3 because the branch does not exist.
If you can create the branch I can submit the pull request.

**Comment by rlove** [comment]
I have a version3 branch in the rlove/utPLSQL just needs a branch in the main repository so I can submit the pull request to it.

**Comment by PaulWalkerUK** [comment]
Apologies for the delay - I'll try to create a v3 branch tomorrow...

**Comment by PaulWalkerUK** [comment]
I've created a "version3" branch
