### ISSUE TITLE
Hardware Requirements Guidance

### ISSUE THREAD

**Issue by kirksgs2** [utPLSQL/utPLSQL#1019]
Does the utplsql community have any guidance on how to spec out hardware and storage for utPLSQL based on either the user counts and / or test case counts?

.

**Comment by jgebal** [comment]
Hi @kirksgs2 
User count is not relevant.
Testcase count could have some impact but I wouldn't see it as something that could bring any trouble on XE database.
Tests are lightweight.
 It's probably more about what the tests are testing.
Do you look for something specific? 
Can you provide more details on your question?

**Comment by kirksgs2** [comment]
For the objects under test, we have a large, shared schema with 43000 objects total, most tables but still quite a bit of utplsql logic.  The shared schema is used across dozens of teams, and all will be using utplsql as much as feasible to test this logic and perhaps inspect key aspects of their DDL.   The only potential limitation may be having repeatable test data for the tests to be idempotent and reliable.    The tests and utplsql will be in their own server and will use dblink to target the objects under test in the large, shared schema.    Our goal is to properly size this utplsql server.    Even though the user count isn't that relevant, we anticipate eventually about 200 developers using utplsql to create and maintain their test cases, and the test case count to grow over time with a few thousand tests added per year, eventually reaching 10-20k tests total.    

I imagine the utplsql box will be cpu and network intensive (due to dblink), not require much RAM as we won't be working with large data sets, and not really require much storage capacity to hold the tests, executions, etc., however, we'd like those assumptions to be validated, and for any capacity guidance given the scenario above. 

Can the community please advise?   Thanks in advance.

**Comment by jgebal** [comment]
Hi @kirksgs2,

First of all, thanks for sharing the details, they bring much more light into the scale and architecture that you have in mind.

My first question is:
**Is this the architecture that you're planning to implement or is an already existing one?**

I have done tests of framework itself, running 100k unit tests in a single run on a small local Dcoker database (4GB RAM only). I don't have exact numbers but I do know utPLSQL was running fine, it just took a while to start a 100k test-run (running all 100k tests).

With 100k tests, runnign a subset of them wouldn't cause any issues from the framework side itself.

What I'm more concerned about is the fact that you plan to run all tests on a remote database!

With the described approach, you doom yourself for problems with:
- performance, lags
- potential issues related to distributed transaction
- concurrency, locks, deadlocks across tests when you have 200 developers developing/testing on a single environment

My key questions would be:

What is the rationale behind remote-test execution? At utPLSQL recommend placing tests in the same schema as the tested code.

Do you have to have all 200 developers on a single DB.

Also, most probably the key challenge will be execution performance of your tests.
It will be mostly depending on the type of tests, type of code under tests, data volume in tested database.

My advise would be:
- test locally, not remotely
- trim down the volume of data in the dev/tests DBs to keep it useful but not heavy
- have several smaller databases, so that each team of 5-10-20 engineers have their own DEV/sandbox
- if you thing of performance tests, have it as a separate set of tests, running on a separate DB (production-like)

It might seem like a challenge, but if done right, it will enable your engineers to accelerate.
Single DB will become a challenge and obstacle with developers stepping on each-other toes.

Hopefully I understood your situation correctly and you will find my response of use.

**Comment by Jaisin12** [comment]
Hi @jgebal,

Thanks for giving insight on utPLSQL.

We are planning to use utPLSQL in our organization around 500+ developers, is utPLSQL is Active Directory Aware? So that it will be easy to configure the users at once with single sign on.

As well as any suggestions on the storage space to start with 500gb or 1TB? Along with growth speculations around 2-3 years will be highly appreciated.

**Comment by mathewbutler** [comment]
Hi @Jaisin12,

Do you work on the same project as @kirksgs2 who originally raised this issue? 

If not, whilst you raise related questions – it might be easier to separate your questions into a new and separate issue so that the thread of question and response is clear (a number of questions were previously asked by @jgebal and awaiting response. Keeping two issues will help ensure that the questions and any responses are not lost.

As to your questions;

- Is utPLSQL Active Directory Aware, and can it support single sign-on?

  - I’m not aware of anything in utPLSQL that would prevent active directory integration. As I understand this integration the user would still authenticate to the database, but the database would delegate to AD. You don’t say what version of the database you are using, here’s a 12.1 link as a starting point for Oracle RDBMS AD integration https://docs.oracle.com/database/121/NTQRF/active_dir.htm#NTQRF270 

- Are there any recommendations for storage space? 

  - utplsql is installed in its own schema, the framework doesn’t store any persistent data worth mentioning. There is a cache of tests held for those that need to be executed. How much memory is used depends on how many tests a developer has deployed, and a developer need not deploy all her/his tests at one time – she/he may deploy only those tests covering a specific area of change. See below for some idea of on disk size of tests.

- What about storage growth over 2-3 years?

  - See the previous answer. The storage for tests is probably not relevant – though clearly more space needed the more tests you write. As an example – I work on a project that has been writing tests for the last 5 years. We have converted all our tests to utPLSQL – we have roughly 320 test packages and around 4500 tests. The on disk size of the tests and some test utilities we have put together is less than 25Mb. 

  - I expect that the drivers for your server sizing will be application workload driven, and also driven by the number of concurrent users you need to support. You suggest there may be 500 developers, but some smaller number of this population with be concurrently doing work, plus you may have some automating build pipelines that may be driving some usage. At peak on my reference project we had ~60 developers running with our application code on a 2 vCPU linux guest, with 16GB RAM – for our application our DB was oversized with a 3GB SGA. But YMMV. I suggest that you will need to carry out some modelling and as with all things that are application dependent make an educated safe “guess”.

I hope this answers your questions. If not, or you have further questions, can you please copy-past your question and this response into a new issue and the thread can be picked up there.

Kind regards,

**Comment by Jaisin12** [comment]
Hi @mathewbutler ,
 
Yes, I work with @kirksgs2. Also, I appreciate your quick response.

Thank you!!
