### ISSUE TITLE
what versions of Oracle DB utPLSQL V3 is compatible?

### ISSUE THREAD

**Issue by vasanthsumanath** [utPLSQL/utPLSQL#1032]

**Comment by vasanthsumanath** [comment]
I am new to utPLSQL, I am quite impressed by utPLSQL and planning to use it as a common TDD framework for all PLSQL related developments. Every teams are in different Oracle DB version starting from V9i to 12c. So would like to understand can utPLSQL V3 be used for all oracle Version or we have any pre- requisite like oracle DB should be 11g R2 or above?. Kindly help.

**Comment by pesse** [comment]
Hi @vasanthsumanath 
utPLSQL V3 can be run on every Oracle database since 11g R2. This is also stated in the [manual](http://utplsql.org/utPLSQL/latest/userguide/install.html#supported-database-versions), but maybe we should announce it also more prominently on the utplsql.org website.
Please be aware that the framework might be discontinued for 11g at some point. If you have any chance I would highly encourage you to try pushing for more recent Oracle versions (I know it's not always possible).

**Comment by vasanthsumanath** [comment]
> Hi @vasanthsumanath
> utPLSQL V3 can be run on every Oracle database since 11g R2. This is also stated in the [manual](http://utplsql.org/utPLSQL/latest/userguide/install.html#supported-database-versions), but maybe we should announce it also more prominently on the utplsql.org website.
> Please be aware that the framework might be discontinued for 11g at some point. If you have any chance I would highly encourage you to try pushing for more recent Oracle versions (I know it's not always possible).

Thanks @pesse , Apologise Probably I missed that part. Yes its clear now. 
On Upgrading the DB version, Ya I understand, but as rightly mentioned its not always possible as there is a look on the Packaged app this is purchased from vendor and also lot of dependancy both internal and External.

**Comment by pesse** [comment]
@vasanthsumanath, for you have a unique perspective I don't have: Where would you have looked for the DB compatibility information? Release notes? Website?
Would be great if you could tell me so we can improve!
