### ISSUE TITLE
Inbuilt Archival Mechanism of UTPLSQL

### ISSUE THREAD

**Issue by PriyankaKeer** [utPLSQL/utPLSQL#1123]
Hi Team,

Is there any inbuilt Archival Mechanism of UTPLSQL?

Thanks in Advance!

**Comment by PhilippSalvisberg** [comment]
No. - What do you expect exactly?

**Comment by pesse** [comment]
For utPLSQL 3, it was a conscious design decision to *not* store the run results. This is the job of your CI software (e.g. Jenkins) or your PlugIn (SQL Developer PlugIn does store a history, DataGrip PlugIn does also).
There is also the possibility to simply store the results when you run them as `select * from table(ut.run())`
There is also an Apex App that provides a lightweight solution to storing run results: https://github.com/triologygmbh/utPLSQL-APEX

**Comment by PriyankaKeer** [comment]
> No. - What do you expect exactly?
Hi,

Apologize for the delayed response..
 
If the test results are stored in existing utPLSQL tables,the size of the schema goes increasing
so i was asking if there is any mechanism to archive the data or tables which minimises the schema size.

Thanks in Advance!

**Comment by pesse** [comment]
I think this issue is resolved: utPLSQL v3 does not store any data despite the temporary data it needs during running the tests and cache data about the structure of the test packages/annotations it uses to enhance performance.

An increase in schema size might happen when, over time, more and more test packages are registered and therefore annotations are cached. The cache, however, is not necessary and can be disabled.
The run results are not stored.
