### ISSUE TITLE
Varchar2 constants are not defined when running all tests

### ISSUE THREAD

**Issue by FlyingWhaleEng** [utPLSQL/utPLSQL#1163]
**Describe the bug**
Varchar2 constants are not defined when running  test if they are declared below 152 lines. 
Constants in tests are in the scope of procedures. The code compiles successfully.
Other type constants work.

**Provide version info**
utPLSQL - Version 3
Information about utPLSQL and Database version, 

```sql
...
line 153:  SUBJECT2       constant varchar2(20) := 'New subject'; 
...
procedure addMessageSmppidValidSmppIdSeq is
begin
 ...
  dbms_output.put_line(SUBJECT2);
 ...
end;
```

**Information about client software**
PLSQL Developer  14.0.3.1981

**To Reproduce**
1. call UT$IS2_INTERFACE.addMessageSmppidValidSmppIdSeq();
2. Click output 
3. Subject2 not displayed

**Expected behavior**
Subject2 is displayed

**Comment by jgebal** [comment]
Hi @FlyingWhaleEng 
I'm trying to understand the issue you have described and unfortunately I'm unable to.
Please provide the following:
- exact version of utPLSQL framework that you use
- exact steps to reproduce this problem (so that I can see the problem on my machine too)

Without that, we cannot help you.

**Comment by jgebal** [comment]
@FlyingWhaleEng - any response?

**Comment by jgebal** [comment]
Closing - no reply from author
