### ISSUE TITLE
Code coverage report produces with zero records

### ISSUE THREAD

**Issue by 00gut** [utPLSQL/utPLSQL#1262]
This test package has 4 test cases where each one of this test invokes Adcom_Util_API.Get_Text_Time function.
  
  
![image](https://github.com/utPLSQL/utPLSQL/assets/139113659/4c58a7c8-9710-4117-8c81-6fabb2171840)

![image](https://github.com/utPLSQL/utPLSQL/assets/139113659/86db9971-1d51-467d-8975-e21e242b5b80)

I have run the test as follows 
ut.run(ut_coverage_html_reporter(), a_include_object_expr => '^uttest_adcom_util');

The test suite ran successfully

However, the code coverage feature is unable to capture the coverage info for the above test function
  
![image](https://github.com/utPLSQL/utPLSQL/assets/139113659/1f1d64c3-7eda-43ab-80dd-166cb1c41905)

**Comment by lwasylow** [comment]
Can you please follow a template to submit issues?
Which version of UTPLSQL you have.
Which version of database.
What is exactly a command you are running?
Are you using plugin for your IDE, if so you have to raise issue in the plugin repository.

Thanks Lukasz

**Comment by U-Thathsarani** [comment]
utPLSQL version – version 3.1.14  
version of database – Oracle 19c
I have run the test using 
ut.run(ut_coverage_html_reporter(), a_include_object_expr => '^uttest_adcom_util');

**Comment by lwasylow** [comment]
Hi
Can you confirm below as per documentation.
In order to be able to gather coverage information, the user executing unit tests needs to be either:

The owner of the code that is being tested
Have the following privileges to be able to gather coverage on code owned by other users:
create any procedure system privilege
execute privilege on the code that is being tested (not only the unit tests) or execute any procedure system privilege
If you have execute privilege on the code that is being tested, but do not have create any procedure system privilege, then the code that is being tested will be reported as not covered (coverage = 0%). If you have execute privilege only on the unit tests, but do not have execute privilege on the code that is being tested, the code will not be reported by coverage - as if it did not exist in the database. If the code that is being tested is compiled as NATIVE, the code coverage will not be reported as well.

**Comment by 00tgu** [comment]
I have all privileges and tested it already

**Comment by lwasylow** [comment]
Please attach a code you using so I can replicate an issue.
The lack of objects suggest issue with visibility of the package or some bug when resolving regex.
Can you confirm that it works using  `a_include_objects`?
Or even without include?

**Comment by 00tgu** [comment]
create or replace package uttest_adcom_util is

  -- Purpose : Test the Adcom Util package Get_Text_Time function
  
   --%suite(Adcom Util package - Get_Text_Time function)
   
   --%test(Returns a time text when a number variable with one integer is passed)
   PROCEDURE test_case1;
   
   --%test(Returns a time text when a number variable with one integer, one decimal is passed)
   PROCEDURE test_case2;
   
   --%test(Returns a time text when a number variable with one integer, two decimals are passed)
   PROCEDURE test_case3;
   
   --%test(Returns a time text when a number variable with only a decimal value is passed)
   PROCEDURE test_case4;

end uttest_adcom_util;
/
CREATE OR REPLACE PACKAGE BODY uttest_adcom_util IS
   PROCEDURE test_case1 IS
   BEGIN
      ut.expect(Adcom_Util_API.Get_Text_Time('1')).to_equal('01:00');
   END;

   PROCEDURE test_case2 IS
   BEGIN
      ut.expect(Adcom_Util_API.Get_Text_Time('1.5')).to_equal('01:30');
   END;
   
   PROCEDURE test_case3 IS
   BEGIN
      ut.expect(Adcom_Util_API.Get_Text_Time('1.53')).to_equal('01:32');
   END;

   
   PROCEDURE test_case4 IS
   BEGIN
      ut.expect(Adcom_Util_API.Get_Text_Time('0.5')).to_equal('00:30');
   END;

END uttest_adcom_util;
/

**Comment by 00tgu** [comment]
It didn't work without a_include_object_expr
![image](https://github.com/utPLSQL/utPLSQL/assets/139113659/f4c3cc08-0712-48eb-b312-65c5e05c3a28)
![image](https://github.com/utPLSQL/utPLSQL/assets/139113659/92e26961-bd8d-4ae4-bff3-d92fde94fc18)

**Comment by jgebal** [comment]
Your DB is running out of PGA memmory wjen trying to produce a coverage report fir entire schema. 
Your schema must be big (lots of code) or your PGA limit is low.

**Comment by lwasylow** [comment]
@00gut just noticed very important detail.
You are adding a test package as included object but a one you want coverage for is `Adcom... `
Try that please.

**Comment by lwasylow** [comment]
Closing as no more comms.
