### ISSUE TITLE
Build Server?

### ISSUE THREAD

**Issue by DDieterich** [utPLSQL/utPLSQL#13]
Do we have any build servers?  (Something that will build and test utPLSQL.)

**Comment by Shoelace** [comment]
obviously the best thign for a build server would be for it to check it compiles (ie installs) and then run a set of unit tests.

which gives us 2 issues
1. need access to a running oracle instance to run the installation
and
2. i dont believe there _are_ any unititests for utplsql


my first thogth was https://cloud.oracle.com  but it costs money

otherwise
https://travis-ci.org seems to be common for github CI systems. and https://github.com/cbandy/travis-oracle has details on getting oracle to be available to the CI build.

i might have an experiment on one of my personal projects.. and report back with how i go..

but that still leaves the issue of needed unit test to test utplsql.. presumable written in utplsql.
(ouroboros anyone?)

**Comment by Shoelace** [comment]
well that worked surprisingly well.

see
https://travis-ci.org/Shoelace/utPLSQL/builds/112296169

no tests performed.. but a successful installation.

**Comment by DDieterich** [comment]
Indeed!  I look forward to getting our first utPLSQL v3 unit tests up and running...

**Comment by jgebal** [comment]
@Shoelace That is very impressive and promising.
Great thing to have CI for such project :+1:

**Comment by Shoelace** [comment]
several question.
* is there any point in having unit tests for v2? 
* would they be useful for regression testing? or not because the api is expected to change a bit.
* does anyone have any tests generate already?

and lastly..if i was to start creating some.. where should i start.. i was thinking probably ut_assert.

**Comment by jgebal** [comment]
I would start from testing the things developer would normally use so utassert API seems like a good start point.
I would start by focusing on what is expected in v3 to minimize overhead and time invested in backward compatibility.

**Comment by rlove** [comment]
This is very nice work.      We really need to ask ourselves how do we effectively use utPLSQL to test utPLSQL.      I also think that code design that allows for this may be easier with a new v3 code base verses trying to get it working with v2.   Granted with have to have a v3 code base.

**Comment by Shoelace** [comment]
i just found instructions for installing oracle-xe via apt.
http://www.oracle.com/technetwork/topics/linux/xe-on-kubuntu-087822.html

i just tried it on an ubuntu VM and it installed 10g
```
Connected to:
Oracle Database 10g Express Edition Release 10.2.0.1.0 - Production
```
so that coyuld be useful..

other options include using a docker build
https://hub.docker.com/r/wnameless/oracle-xe-11g/

**Comment by jgebal** [comment]
Publishing Oracle binaries as docker image violates Oracle License agreement.
https://community.oracle.com/thread/3629935?start=0
The only options seems to be:
- have private docker, that is not shared
- use what we have now
- try the 11g xe on kubuntu via apt

It would be great if we would manage to have Travis do building/deploying and testing on both Oracle 11 and 12.

**Comment by Shoelace** [comment]
the apt that i found from oracle is only 10g..  the 11g on the travis build at the moment is downloading the source and installing it each time also. (just not via apt)
it just adds several minutes to the build time and seems like a waste of bandwidth so i was looking for alternative solutions.

there is no 12c XE  and the full 12c is like 2.5GB to download.

it seems like the easiest (best?) solution would be to have hosted instances of the db and just get travis to connect to them remotely..

its something to think about anyway.

**Comment by jgebal** [comment]
Not many options for real development.
I have my own Jenkins running on VM on my home laptop but I don't think exposing it on the internet would be good idea. It's running 11g XE anyway.
I have 12c on Oracle Linux VM too - downloadable from Oracle but not using it at the moment.
Perfect solution would be to have some hosted (free) CI with ability ot have Oracle 11/12 as pluggable components that do not require build.

On the other hand we could try to setup 12c on Travis, as long as it's OK with licencing.
Even if build takes long, it's still a huge value for the project.

**Comment by PaulWalkerUK** [comment]
My only experience is setting up XE on a local machine (and similar to @jgebal, I have no intention of opening that up to the internet :wink:) . I'd be wary about automating anything in the cloud - I've no idea what the licensing situation would be. It's certainly a nice idea though

**Comment by rlove** [comment]
I have ordered a new server for build management.    I plan to install Oracle 11 and 12 so we can automatically test both.   Right now I am leaning to installing Jenkins to manage the builds.    And then use the GitHub Plugins to validate pull requests.

**Comment by rlove** [comment]
Although I have build server we ended up using Travis-CI and it seems to be working well because everyone can see it an use it.
