### ISSUE TITLE
Stubbing of procedure/function

### ISSUE THREAD

**Issue by morty321** [utPLSQL/utPLSQL#130]
Hello,

I've used utPLSQL for a time now, and while I have enjoyed using it, one thing I am missing is the ability to stub procedures and/or functions. 

As an over-simplified example I have a function (foo) and a procedure (bar). "bar" prints out the result of "foo". "foo" can easily be unit tested as it only relies on itself and is not a problem. 

The problem however is "bar" as the functionality of "bar" depends on the functionality of "foo". Now, depending on the complexity of the code it means I would have to not only test the paths that "bar" takes, but also all the paths that the inputs into "bar" would take once they path through "foo". 

At this point it is not possible to unit test "bar", and all the testing for "bar" is integration testing. It can never be independent because it depends on the functionality of "foo". Ideally I would want to be able to stub foo and decide what the outputs of "foo" is so that any functionality foo otherwise has is decided at the runtime of the unit test. 
```
function foo(return_this in boolean)
return boolean
is
begin
	return return_this
end foo;

procedure bar(input_boolean in boolean)
is
begin
	dbms_output.put_line(foo(return_this => input_boolean));
end bar;
```
This is merely a suggestion to what I believe would be a nice implementation to what is already a great testing package. I tried looking over the documentation as well as planned changes for version 3 but was unable to find any hinting at stubbing. Please let me know if such functionality already exists or if there are any workarounds for these type of issues. Otherwise I hope this would be considered for the development on utPLSQL.

**Comment by Pazus** [comment]
Hello, @morty321 

Currently there is no workaround provided by the framework. Stabbing is mostly limited by the language, but we'll think what can be done. If you have any ideas how stabbing can be implemented, please let us know.

**Comment by jgebal** [comment]
Hi.
Thanks for using UTPLSQL.
Are you using v2 stable or v3 alpha?

**Comment by jgebal** [comment]
To your question on stubbing.
I don't think its easily doable in PLSQL as your code has tight, compiled dependencies.
If you get rid of that by using synonyms everywhere, you face another issue - you need a private database for everyone because when you run your code and replace synonyms, it is global and affects everyone.
So stubbing is not so much function of the framework itself, it is design of db dependencies.

Having said that. It seems that you eat to do something that is not really needed.
Stubbing and mocking will make your tests less valuable and harder to maintain.
The only thin to stub/mock (if anything), should be the data under test.

Here is a great talk from Ian Cooper about TDD failures due to the misunderstanding of concept of unit test that grew over the years.
https://vimeo.com/68375232

And an interview with him with the essence of the message from the talk.
https://youtu.be/HNjlJpuA5kQ

**Comment by jgebal** [comment]
@morty321 
What I had in mind when I was talking about synonyms is that everywhere in your code you reference other procedure by synonym.
Example:
```
create package foo is
  procedure blah;
  procedure ding;
end;
/

create synonym a_foo for foo;

create package body foo is

  procedure blah is
  begin
    a_foo.ding;
  end;

  procedure ding is
  begin
    null;
  end;
end;
/
```

Referencing everything by synonym is unnatural (specially within the context of single package body).
It might work quite if you would like to limit stubbing to procedures outside of context of a single package. 
Still this means that your database code needs to be designed for that purpose.

**Comment by jgebal** [comment]
One thing that I do not like about the idea of Unit Test as a test that is testing single unit of code in isolation from other code is that it's killing the purpose.

Taking my example above:
```
create package body foo is

  procedure blah is
  begin
    ding;
  end;

  procedure ding is
  begin
    --do stuff;
  end;
end;
/
```
If I now decide to inline my ding procedure so my code looks like this:
```
create package body foo is

  procedure blah is
  begin
    --do stuff;
  end;
end;
/
```
- My tests for `ding` are failing.
- My tests for `blah` don't test the thing anymore.

Testing in too much isolation is very dangerous.
Also, we usually build systems, not individual pieces of code.
`blah` doesn't make sense id `ding` is not working or is not there.
I would do one of two:
- test `blah` and `ding` together
- test only `ding` as it's doing the 'stuff' and `blah` is just a wrapper
It is all relative and depends on the use case.
Hope that this clarifies a bit on risks and dangers of mocking and stubbing.

**Comment by janihur** [comment]
As already stated by @Pazus and @jgebal because in PL/SQL a subprogram (or a package or a block) is not a [first-class function](https://en.wikipedia.org/wiki/First-class_function) the language itself doesn't provide any mechanism for dynamically pick the executed subprogram. This can be worked around e.g. with dynamic PL/SQL but IMO that's not the worth of the trouble. AFAICS this means "stubbing" is impossible in PL/SQL.

However [Oracle Objects](http://docs.oracle.com/cd/E11882_01/appdev.112/e11822/adobjplsql.htm#ADOBJ070) are first-class citizens so if one models the PL/SQL code as objects instead of  as packages then [dependency injection](http://stackoverflow.com/q/130794/272735) can be used.
