### ISSUE TITLE
ORA-02289: sequence does not exist

### ISSUE THREAD

**Issue by tehnicaorg** [utPLSQL/utPLSQL#29]
Our DBA installed the utplsql package (without using/allowing synonyms). I've tried to use it but I get an error.
The error comes if either I use the name of an existing `ut_` package or not.

```
SQL> exec utp.utplsql.run('ut_xxxxxxxx');
begin utp.utplsql.run('ut_xxxxxxxx'); end;
ORA-02291: Integritäts-Constraint (UTP.UTR_ERROR_OUTCOME_FK) verletzt - übergeordneter Schlüssel nicht gefunden
ORA-06512: in "UTP.UTRERROR", Zeile 149
ORA-06512: in "UTP.UTRERROR", Zeile 324
ORA-06512: in "UTP.UTROUTCOME", Zeile 146
ORA-01400: Einfügen von NULL in ("UTP"."UTR_OUTCOME"."RUN_ID") nicht möglich
ORA-06512: in "UTP.UTRESULT2", Zeile 72
ORA-06512: in "UTP.UTASSERT2", Zeile 137
ORA-06512: in "UTP.UTASSERT", Zeile 49
ORA-06512: in "UTP.UTPLSQL", Zeile 1104
ORA-02289: Sequence ist nicht vorhanden.
ORA-06512: in "UTP.UTPLSQL", Zeile 1379
ORA-06512: in Zeile 1
```

I'll also try to get some help from the DBA next week to trace the code; now I can only see the traceback, but not which sequence is missing.

There are 10 sequences under the schema utp, almost everyone of them start with `ut_`. Just one doesn't: `UTPLSQL_RUNNUM_SEQ`.

**Comment by rlove** [comment]
The synonyms are required to make utPLSQL work.   Because packages are defined with the AUTHID of CURRENT_USER.     This means the current user need to see those objects and can not see them without the synonyms.     We don't allow new PUBLIC synonyms in our database.

So I use the following script to create a script that generates private synonyms  in each schema that I want tests to be in:

select 'create synonym '||object_name||' for '||object_name||';' from all_objects
where owner='UTPSQL_SCHEMA_NAME_REPLACEME'' 
and object_name like 'UT%' 
and object_name not in ('UT_UTOUTPUT', 'UT_UTREPORT')
and object_type IN ('PACKAGE', 'TABLE', 'VIEW', 'SEQUENCE');

**Comment by tehnicaorg** [comment]
Thanks Robert, it works after creating the synonyms (even non-public). 

Maybe the documentation should be improved: [Step 1. Install (and Upgrade) utPLSQL](https://utplsql.github.io/docs/fourstep.html)

> **Note** If the schema in question does not have the ability to create and drop public synonyms or execute privilege on DBMS_PIPE, you may get error messages when installing. However, **utPLSQL will still function correctly**.

Script was missing the schema name in *create synonym xxx for* **yyy***.xxx*:
```
SELECT 'create synonym ' || object_name || ' for UTPSQL_SCHEMA_NAME_REPLACEME.' || object_name || ';'
  FROM all_objects
 WHERE owner = upper('UTPSQL_SCHEMA_NAME_REPLACEME')
       AND object_name LIKE 'UT%'
       AND object_name NOT IN ('UT_UTOUTPUT', 'UT_UTREPORT')
       AND object_type IN ('PACKAGE', 'TABLE', 'VIEW', 'SEQUENCE');
```
