### ISSUE TITLE
Develop assertion procedures

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#30]
We need to migrate assertions from v2 and develop new. Who can do that?

**Comment by jgebal** [comment]
I can.

**Comment by Shoelace** [comment]
well the v2 asserts are essentially.. equal isnull, isnotnull, exists, and throws

with the new expect syntax it would be easy enough to add things like `ut.expect(number).lower_than(number)`  and `ut.expect(date).is_before(date)` 

i think the list should be (with these names) 
* to_equal
* is_null
* is_existing_object
* is_less_than 
* is_greater_than
* is_before
* is_after
* to_raise

and NOT versions of the above.. 
i dont know if with the `ut.expect.to_()` syntax you coudl have a generic `not`  ie `ut.expect().to_(not())`

i dont know if we need/want `is_less_than_or_equal`  also

**Comment by rlove** [comment]
To add to @Shoelace list.

Applies to all data types.
- is_not_null
- is _between (if type supports greater/less than)
- to_match_query_value('select value from table where id= 3')

VARCHAR2 Comparisons
- is_like
- is_regex_match

Table / View Comparisons (ideas at this point)
  - ut.expect_table_or_view(‘obj_name’, message=>’a’).contents_to_equal(‘obj_name’,'optional where')   
  - ut.expect_table_or_view(‘obj_name’).row_count(3,  row_count(3, where_stmt => ‘0=0’)   
  - ut.expect_table_or_view('obj_name').ddl_columns_match(‘object_name’)
  - _obj_name_ can include owner, and wonder if we need to accept inline views

Note v2 has a Comparisons for
  - Scalar Types: boolean, varchar2, date  (You already support more)
  - Tables  (My list above covers these plus more)
  - DBMS_Output 
  - Collections
  - Raises/Throws (Exception management)
  - Files
  - Pipes

**Comment by Pazus** [comment]
For ref_cursor: assertions of row count (exact comparison), row count greater/less then, assert that at least 1 row is returned, assert no rows exist

**Comment by Pazus** [comment]
`ut.expect_this` as a shortcut for the simplies equivalent of `ut_assert.this`

**Comment by jgebal** [comment]
With #73 we are getting the following 

Matchers|
-----------
equal |
be_true |

Assertions|
-----------
to_equal |
to_be_null |
to_be_not_null |
to_be_like |
to_match |
to_ |
The `to_` assertion can be used with any matcher (currently `equal`, `be_true` )

Assertions are grouped by compared data type so that we get a compile-time error, when trying to use an assertion that is not available for specific data-type (`to_match`, to_be_like`)
The `to_equal` assertion is available for any data type and will make test fail when comparing wrong data types.

**Comment by jgebal** [comment]
I will put the requests for new asserts and expectation as individual requests.
