### ISSUE TITLE
Random order of test execution

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#422]
Define suite level annotation to shuffle tests on execution

**Comment by jgebal** [comment]
It should be a runtime paramerer I think.
This way you can easily check for test independency. 
Also, do we want to have random or simply reverse order?

**Comment by mathewbutler** [comment]
On of the principles of xunit test approaches is that tests should be independent and so relying on ordering of tests (outside of before or beforeall annotation) is considered "a bad thing". 

Maintaining independent tests means that it is easier to diagnose failed test since the programmer only needs to look at a single test scope to understand everything needed to diagnose. 

Enabling this capability feels like a change in direction of ethos of a test suite. 

Just my 0.2c 😀

**Comment by jgebal** [comment]
That is why it should be a runtime parameter, not an annotation I think.
Order (random or not) should not be part of test-suite definition.

I love the idea of random or even simply reverse order of execution in suite.
The ordering should not affect the setup/cleanup order though.

**Comment by jgebal** [comment]
>Enabling this capability feels like a change in direction of ethos of a test suite

@mathewbutler - It would definitely be a positive change.

**Comment by mathewbutler** [comment]
@jgebal I’m just saying that we shouldn’t introduce anything that enables a repeatable order of execution of tests. Random is by definition not reliably repeatable, so fine.

**Comment by lwasylow** [comment]
Is this still planned?

**Comment by jgebal** [comment]
Yes. And this feature should be quite easy to implement now (hopefully) since the suote is build by running SQL on cache.
The only thing to confirm is that it will not have negative impact on clients (SQLDeveloper)

**Comment by PhilippSalvisberg** [comment]
The SQL Developer extension does not directly executes the tests. It just calls `ut.run` or `ut_runner.run`. Everything is fine as long as it can rely on the sort order provided by the reporters.
