### ISSUE TITLE
authid owner package to access dba_ view

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#440]
`ut_metadata` is `authid current_user` which means to use dba_views *the user executing tests* has to have privs to query `dba` views

I think it's wrong - DBA should grant access to dba views to the framework not to the users implementing tests, so we need another package implementing logic with `authid owner`

**Comment by jgebal** [comment]
The decision to use DBA views with `authid current user` was done on purpose.
This is because of privilege model in Oracle.
If package is authid current user, then both direct grants as well as grants applied through role are considered. That way, user invoking the tests can have `select_catalog` role granted or `select any dictionary` system privilege granted and the DBA views will be accessible to him when invoking the package.

If we would go with `authid definer` then all DBA views would need to be granted directly to owner of UT# packages.
That would be a no-go for most Admins as granting access directly to DBA views is considered a bad practice and can be a causing security vulnerability.

I would not change the current behavior.

**Comment by mathewbutler** [comment]
Just to add that it looks like get_dba_view also downgrades requests for dba_ access to request for access to all_. That is, if the privilege isn't available then the code will still work. 

It was a surprise to see this downgrade behaviour. As neither the function names or the function documentation make it clear that this is what will happen.
