### ISSUE TITLE
Testing PROCEDURES

### ISSUE THREAD

**Issue by phill-jacobs** [utPLSQL/utPLSQL#447]
I am new to utPLSQL and evaluating whether we can use it within our Development department.  So far as I can see, all testing is based upon being able to check the values returned by FUNCTIONS.  Our existing APIs use PROCEDURES mostly, though there are some functions.  What approach should we follow to test the behaviour of procedures?  Am I missing something, or does utPLSQL only cover a limited scope of testing for an API?

**Comment by pocelka** [comment]
I guess it depends. I have the same problem how to implement automatic testing to our existing code. The problem is more visible when your application logic is all about data and complex business rules. 

The "problem" is that with utPLSQL you need to change the way how you think about the code. utPLSQL leverages from TDD - Test drive development, which basically means that you start with writting test scripts instead of rushing into coding.

Existing code might have to be refactored to be able to use with utPLSQL. If it can't be refactory

**Comment by phill-jacobs** [comment]
That's a helpful answer: thank you.

**Comment by jgebal** [comment]
Hi @phill-jacobs , 
We didn't manage to prepare a set of high quality examples and tutorials on TDD and unit testing in Oracle Database yet. That is one of the items on the quite long TODO list.

You can have a look at some basic examples in our [demo project](https://github.com/utPLSQL/utPLSQL-demo-project). Hopefully they will give some light.

**Comment by pesse** [comment]
Hi @phill-jacobs 

I'm in a similar situation. What I did was making use of utPLSQL's transactional approach. I got setup methods for my tests, including special test data, then run the procedures and checking the results via selects etc.
After the test is done everything is rolled back.
Of course you have to make sure not using PRAGMA AUTONOMOUS_TRANSACTION or DDL via EXECUTE IMMEDIATE, but besides that you can securely insert any test data you want to prepare your test.

**Comment by jgebal** [comment]
@phill-jacobs
Did you have a look at our demo project and example of a test of procedure `remove_rooms_by_name`?
https://github.com/utPLSQL/utPLSQL-demo-project/blob/develop/test/remove_rooms_by_name/test_remove_rooms_by_name.pkb

It shows an example of tests for procedure that operates on table data.

Let me know if thst hepls.

**Comment by jgebal** [comment]
Closing - inactive
