### ISSUE TITLE
Tigger ut run with coverage from the same sql session multiple times, only the first run create new runid

### ISSUE THREAD

**Issue by email2ying** [utPLSQL/utPLSQL#513]
Steps to reproduce:
1. login to db, run a ut with coverage enabled
2. new run_id created in PLSQL_PROFILER_RUNS
3. run the ut again from same session
3. no new run_id created in PLSQL_PROFILER_RUNS, the same coverage result as the first run returns

**Comment by email2ying** [comment]
I got this issue from oracle 11.2. Maybe that is the reason.

**Comment by pesse** [comment]
Can you tell us which version of utPLSQL you use?

**Comment by email2ying** [comment]
utPLSQL - Version v3.0.2.938

**Comment by jgebal** [comment]
It is v3.0.2
- Can you check and see if reset package state helps
- can you check if executing dbms_profiler.stop helps?
- check if the same issue occurs when you run the same commands from SQLPLUS

**Comment by email2ying** [comment]
reset package state helps , but it somehow repressed the dbms_output
dbms_profiler.stop_profiler doesn't help
Seems issue when running same commands from sqlplus

**Comment by jgebal** [comment]
@email2ying 
I've checked again on 11.2.0.2 XE using `v3.0.2`
There was an undocumented bug in coverage reporter. It was already fixed in `v3.0.3` as part of #417.

Yesterday I was checking using develop version of the framework - that is why I could not see the issue occur.

Once you get v3.0.3 or above installed -> it will work fine.
