### ISSUE TITLE
3.0.4: ORA-00001: unique constraint (UT3.UT_ANNOTATION_CACHE_PK) violated

### ISSUE THREAD

**Issue by tkleiber** [utPLSQL/utPLSQL#516]
We run on Oracle EE 11.2.0.4 and get this error:

Error report -
ORA-00001: unique constraint (UT3.UT_ANNOTATION_CACHE_PK) violated
ORA-06512: at "UT3.UT_RUNNER", line 101
ORA-06512: at "UT3.UT", line 105
ORA-06512: at "UT3.UT", line 270
ORA-06512: at "UT3.UT", line 322
ORA-06512: at line 2
00001. 00000 -  "unique constraint (%s.%s) violated"
*Cause:    An UPDATE or INSERT statement attempted to insert a duplicate key.
           For Trusted Oracle configured in DBMS MAC mode, you may see
           this message if a duplicate entry exists at a different level.
*Action:   Either remove the unique restriction or do not insert the key.

Downgrading to 3.0.3 fix the problem.

**Comment by jgebal** [comment]
I think I've encountered this issue before.
It will be fixed with refactoring on annotation parser.
I believe one of your suites has something like this:
```sql
package test_package is
  --%suite(first annotation)
  --%test(second annotation)
  procedure test_procedure_1;
  --%test(third annotation)
  procedure test_procedure_2;
end;
```

The annotations on top are allocated to both suite as well as first test.
So you end up with annotations:
suite level has:
- first annotation
- second annotation

test procedure 1 has:
- **first annotation**
- **second annotation**

test procedure 2 has:
- third annotation

To avoid this issue in 3.0.4 make sure you separate suite-level annotations from test level annotations.

In next versions this behaviour will change so that the above case will cause no suite level annotations to be created.
**This means that your suite will no longer be valid in that case.**

A valid test package would be:
```sql
package test_package is
  --%suite(first annotation)

  --%test(second annotation)
  procedure test_procedure_1;
  --%test(third annotation)
  procedure test_procedure_2;
end;
```

**Notice:
  The empty line is used to separate annotations associated with package from annotations associated with procedure.**

**Comment by tkleiber** [comment]
Yes, this was the problem. Have double checked this with the formatters in our IDE's, which let the empty line in the code now. But will be good the fix this in the future. 
Thanks!

**Comment by jgebal** [comment]
@tkleiber Can you join the Slack and share your experiences with utPLSQL v3 so far?

**Comment by tkleiber** [comment]
Will give a presentation next week at DOAG2017, why we decide us for utPLSQL v3.
