### ISSUE TITLE
Code coverage id excludign some executable lines

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#520]
As pointed by @tkleiber in his presentation, for some lines, utPLSQL is not showing coverage.
https://www.slideshare.net/tkleiber/plsql-drum-test-automatisiere-wer-sich-sich-ewig-bindet-doag-2017/58

The coverage filtering for false positives/negatives needs to be improved to avoid this issue.

To reproduce, use the example from slide.

**Comment by tkleiber** [comment]
I'm not sure what you meant. The difference in comparing the reports in ci  
from ruby-plsql-spec and utplsql on page 58 is because in the ruby feature branch (https://github.com/tkleiber/de.kleiber.demos.plsql.testing.unit/tree/feature/ruby) only  a new ruby test is created and called, so there is really no coverage from utplsql.

Anaway here you have too the test script from the presentation:
[utplsql_scripts.txt](https://github.com/utPLSQL/utPLSQL/files/1501205/utplsql_scripts.txt)

**Comment by jgebal** [comment]
It's probably my German understanding that is causing issues. Looking at slide I got impression that it is showing differences between how utPSQL and ruby-plsql-spec is presenting coverage. In particular that it's not capturing return statement.

If this is not the case, I'd like to close this issue.
@tkleiber let me know if that is fine with you.

**Comment by tkleiber** [comment]
Yes - you can close the issue!
