### ISSUE TITLE
UTPLSQL CLI and multiple schema coverage

### ISSUE THREAD

**Issue by lwasylow** [utPLSQL/utPLSQL#526]
Hi
I believe it would be a beneficial to extend CLI to allow pass more than single schema to get out coverage.

it's possible to run it parallel however and run it same tests one for each schema however 
-test results for both will be same
-coverage results will be different
there are also some other unexepcted results when testing the procedure with PRAGMA_AUTONOMOUSE inside its possible to skew test results of the second run.

I understand that file mapping to relevant sources across schema when objects are same will cause problems, but maybe some mapping .properties would be good.

**Comment by jgebal** [comment]
Hi @lwasylow 
Just to understand your situation, please correct me if I'm wrong.
- you have multiple schemes under test
- you have single (separate) schema containing unit tests

In that case I would split the tests into subsets per tested schema and run for each schema separately.
To easily identify suites per schema you could use `suitepath` annotation and execute multiple runs instead of one:
`utplsql run -p=tests_schema`
  would be replaced by
`utplsql run -p=tests_schema:path1`
`utplsql run -p=tests_schema:path2`
`utplsql run -p=tests_schema:path3`
and so on...

The tests per schema should be well isolated and not lead to any concurrency/locking issues.
That however depends on your database design.


Alternatively you can use file / directory names of your project combined with file mappings and regexp to identify database object across multiple schemes.

We cannot assume that object name without schema name is unique. It would either lead to exceptions when more than one object is found or we would risk providing wrong inforamtion by mapping to one of matching objects (randomly).

**Comment by lwasylow** [comment]
Ok I will try to use a file mapping, should be fairly easy to generate via jenkins and shell into the framework and will report :)

**Comment by jgebal** [comment]
@lwasylow - is this still an issue and is this actionable?
Should we update documentation with more examples maybe?

**Comment by lwasylow** [comment]
I think the documentation update would be great. I spend a good few hours trying to figure out how to approach this and I think managed to use a regex and file mapping to run multiple schemas at same time. However in terms of functionality it's there just not clearly accessible.

**Comment by lwasylow** [comment]
3.1 documentation updates make things much clear.
Closing
