### ISSUE TITLE
get rid of calls to dbms_utility.name_resolve if possible

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#569]
Calls to `dbms_utility.name_resolve` are causing issues in the environments where schema_name and an object within the schema share the same name.
This was raised as an issue in utPLSQL itself:
https://stackoverflow.com/questions/45350935/utplsql-installation-ora-04047-error-when-exec-ut-run/48541758#48541758
And here is a bit of background to that issue from one of IBM forums:
https://www.ibm.com/developerworks/community/forums/html/topic?id=d8087c9d-39c2-4cf3-8e29-8611f48a4d6e

Need to review the need to call  `dbms_utility.name_resolve` functionality as well as ways to efficiently replace it (if it's really needed)

**Comment by Shoelace** [comment]
i added the calls to name_resolve ear;y on. it is _supposed_ to be the way oracle itself resolves the name so maybe its just not catching the exception correctly. 
`ut_metadata.do_resolve` doesnt catch any exceptions so that is probably all thats needed..  

i dont think you can get rid of it otherwise the 'authid current_user' stuff doesnt work for running as not the ut owner.
