### ISSUE TITLE
v2 migration routines. Part 1

### ISSUE THREAD

**Issue by Pazus** [utPLSQL/utPLSQL#61]
Implement routins to migrate current v2 config to v3. In the part one let's introduce generation of the specification of test packages generating annotations for tests/setups/teardowns.

Configuration tables of v2 also has to be taken into account.

By the part 1, the contents of package bodies remain unchanged so all assert call have to be changed manually to use v3 package.

**Comment by jgebal** [comment]
@pazus, can you refresh your branch on this topic?
I can do some testing of migration routines.

**Comment by Pazus** [comment]
I'll do it tonight

**Comment by Pazus** [comment]
actualized the branch

**Comment by jgebal** [comment]
I think the following can be 1:1
```
eq -> to_equal
isnotnull -> to_be_not_null
this -> to_be_true
isnull -> to_be_null
test_failure -> fail?
```

**Comment by jgebal** [comment]
@Pazus I had a chat today at work about approach for migration from v2 to v3.
I think that we could be good with what you have at the moment except for few changes:
[ ] Create a new packaged from existing ones rather then overwrite them, so that `ut_my_package` migrates to `u3_my_package`
[ ] Clone packages existing utplsql v2 packages: `utassert` and `utassert2` into utplsql v3 `ut_assert_migration` / `ut_assert2_migration` do not overwrite  but create a "clone" of them and replace references to them in migrated packages
[ ] use naming conventions to determine what should be migrated (utplsql v2 defines a configurable prefix to be used)
[ ] perform migrations schema by schema or package by package


Also, 
[ ] Have the migration in separate project, as it's not part of utplsql and is not needed for users that didn't use v2 at all.
[ ] Reporting of line number and source where assertion has failed will now pint to the migration package `ut_assert_migration` as a nice to have, we could try to change it (that would require different logic to identify the top level of the framework call stack).
[ ] Add ability to warn / inform that the unit test package is using *deprecated / intermediate* functionality and that action should be taken to have sources fully migrated.

This way we can have v2 and v3 unit tests coexist and validate that after migration out v3 works as expected.

**Comment by jgebal** [comment]
Closing - we now have separate project **[utPLSQL-v2-v3-migration](https://github.com/utPLSQL/utPLSQL-v2-v3-migration)** for this.
