### ISSUE TITLE
UT Coverage HTML Reporter throws SYS.DBMS_PROFILER Error

### ISSUE THREAD

**Issue by GMehrl** [utPLSQL/utPLSQL#716]
Hi everyone,
I have a package 'p_menu' and a related ut package 'p_menu_ut'.
When I execute the p_menu_ut normally, everything works fine.
```
begin
  ut.run('p_menu_ut');
end;
/
```
output:
```
menu
  menu
    check that record is correctly created [,435 sec]
    check that record is correctly read [,073 sec]
    check that record is correctly updated [,163 sec]
    check that record is correctly deleted [,07 sec]
    check that MENU ID is correctly checked [,026 sec]
    check that descriptor is correctly returned [,043 sec]
 
Finished in 1,876193 seconds
6 tests, 0 failed, 0 errored, 0 disabled, 0 warning(s)
```
When I try to execute the same ut package with the html coverage reporter, I receive a Error Message (incl. sys.dbms_profiler)
```
begin
  ut.run('p_menu_ut', ut_coverage_html_reporter());
end;
/
```
output:
```
Error starting at line : 1 in command -
begin
  ut.run('p_menu_ut', ut_coverage_html_reporter());
end;
Error report -
ORA-06528: Error executing PL/SQL profiler
ORA-06512: at "UT3.UT_RUNNER", line 133
ORA-06512: at "SYS.DBMS_PROFILER", line 173
ORA-06512: at "UT3.UT_COVERAGE_HELPER_PROFILER", line 53
ORA-06512: at "UT3.UT_COVERAGE", line 200
ORA-06512: at "UT3.UT_COVERAGE_HTML_REPORTER", line 35
ORA-06512: at "UT3.UT_REPORTER_BASE", line 190
ORA-06512: at "UT3.UT_EVENT_MANAGER", line 39
ORA-06512: at "UT3.UT_RUN", line 71
ORA-06512: at "UT3.UT_SUITE_ITEM", line 53
ORA-06512: at "UT3.UT_RUNNER", line 123
ORA-06512: at "UT3.UT", line 115
ORA-06512: at "UT3.UT", line 306
ORA-06512: at "UT3.UT", line 364
ORA-06512: at line 2
06528. 00000 -  "Error executing PL/SQL profiler"
*Cause:    An error occurred in during execution of a PL/SQL profiler
           procedure.
ORA-06512: at "SYS.DBMS_PROFILER", line 173
ORA-06512: at "UT3.UT_COVERAGE_HELPER_PROFILER", line 53
ORA-06512: at "UT3.UT_COVERAGE", line 200
ORA-06512: at "UT3.UT_COVERAGE_HTML_REPORTER", line 35
ORA-06512: at "UT3.UT_REPORTER_BASE", line 190
ORA-06512: at "UT3.UT_EVENT_MANAGER", line 39
ORA-06512: at "UT3.UT_RUN", line 71
ORA-06512: at "UT3.UT_SUITE_ITEM", line 53
ORA-06512: at "UT3.UT_RUNNER", line 123

ORA-06528: Error executing PL/SQL profiler
ORA-06512: at "SYS.DBMS_PROFILER", line 173
ORA-06512: at "UT3.UT_COVERAGE_HELPER_PROFILER", line 53
ORA-06512: at "UT3.UT_COVERAGE", line 200
ORA-06512: at "UT3.UT_COVERAGE_HTML_REPORTER", line 35
ORA-06512: at "UT3.UT_REPORTER_BASE", line 190
ORA-06512: at "UT3.UT_EVENT_MANAGER", line 39
ORA-06512: at "UT3.UT_RUN", line 71
ORA-06512: at "UT3.UT_SUITE_ITEM", line 53
```

Is there anybody who has an idea to solve this issue?
Thanks,
Guido

**Comment by jgebal** [comment]
- What version of utPLSQL are you using? `select ut.version() from dual`
- What DB version are you on?
- How was the utPLSQL installed? Did you use `install_headless.sql`?
- Is the user running the tests also owner of the package `p_menu_ut`?
- Is the user running the tests also owner of the package `p_menu`?

- Did you read about the dbms_profiler requirements in https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/coverage.md#security-model?

**Comment by GMehrl** [comment]
- utPLSQL Version: v3.1.1.1868

- Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

- yes, we use the `install_headless.sql` script

- Yes, the user is owner of both packages

- Yes, I read those requirements

**Comment by jgebal** [comment]
Seems like profiler tables are missing or not accessible to UT3 user.
Can you investigate on that?

**Comment by GMehrl** [comment]
Sorry for answering late.
The three Profiler Tables are existend in the database but only in the UT3 scheme.
The user of the ut packages has all rights on the UT3 scheme.

Strange:
This morning the ut coverage report works with one mentioned ut package. But this happens only once with a new session. So when I wanted to execute the coverage reporter with another ut package, I received the same error message again. I closed the session and opend another one. Same result: One time it works then, error message...
Have you any idea why it only works once with a new session?

**Comment by jgebal** [comment]
Could be a bug - need to investigate. I didn't run coverage steaight from DB for a while now.
Did you try using utPLSQL-cli?

**Comment by lwasylow** [comment]
Could be that profiler is not being stopped properly after first execution? I did run from db many times and didn't not encounter that issue.
Uninstall profiler and reinstall maybe something with synonyms. Admit its strange and could be some bug.

**Comment by jgebal** [comment]
I've tested this today on 12.1 with utPLSQL v3.1.1 release amd couldn't reproduce (running from SQLDeveloper).
What IDE are you using? Can you try SQLPlus or SQLDeveloper?
Is there a distributed transaction involved (db-link query)?
Currently I ran out of ideas why it can be failing.

Consecutive calls to dbms_profiler.start/stop don't cause any issues so it must be something related to visibility of profiler tables.

**Comment by MalchiasTS** [comment]
Hi, I am working with @GMehrl on this problem and can probably answer some of your questions:
Yes, we did try utPLSQL-cli and sqlplus - but that was no use.
=> Our problem does not seem to be related to the client.
Our IDE of choice is the current stabe version of SQL Developer.

@lwasylow, concerning the profiler: We can use the profiler, as long as it is not called from UT3.
The three profiler tables are located in the UT3 schema.
I just tried a profiler example from Burleson and it worked.

We've got about three dozen runs/records in table PLSQL_PROFILER_RUNS that lead to 1665 records in
PLSQL_PROFILER_UNITS which in turn are referenced by 70,000 record in PLSQL_PROFILER_DATA.

As @GMehrl wrote, the coverage reporter works, if started in a brand new session and for just
one package.
Sometimes a second call to another package works as well. But at some point the next call fails.
In detail: dbms_profiler.stop_profiler crashes after it has written only parts of its buffer to
those three profiler tables mentioned above.

**Comment by jgebal** [comment]
I ran the following test as user `ut3`
```
begin
  dbms_profiler.start_profiler('test');
  dbms_profiler.start_profiler('test');
  null;
  dbms_profiler.stop_profiler;
  dbms_profiler.stop_profiler;
end;
/
```
No errors, so:
- Starting profiler when it's started doesn't cause issues
- Stopping profiler when it's stopped doesn't cause issues

One more test as user `ut3_tester`
```
begin
  ut.run('TEST_BE_LESS_OR_EQUAL',ut_coverage_html_reporter());
end;
/
```
- several executions in a row - no issues.
- executing from two concurrent sessions simultaneously - no issues.

One more test:
```
begin
  ut.run('TEST_BE_LESS_OR_EQUAL',ut_coverage_html_reporter());
  ut.run('TEST_BE_LESS_OR_EQUAL',ut_coverage_html_reporter());
end;
/
```
No issues - produces two HTML reports.

**Comment by jgebal** [comment]
Sorry for not providing any solution, but I just cant find the problem.

**Comment by MalchiasTS** [comment]
@jgebal

> Sorry for not providing any solution, but I just cant find the problem.

We appreciate your trying.

**Comment by jgebal** [comment]
Please keep us updated if you manage to find what is causing this.
It would be good to know the cause of your issue.

**Comment by jyaner** [comment]
I had a similar problem. I have detected that the name of the package that contained the tests had more than 30 characters. I changed the name to a shorter one and now it works correctly

Apologies for English. It's a google translation

**Comment by SDepn** [comment]
Hi,

I am working with @GMehrl and @MalchiasTS on this problem. I was able to break the problem further down, but didn't find the root cause yet. As @jyaner mentioned it seems to be length related. Although i'm not convinced that the package name is the problem. 

For all my tests i used:
- SQL Developer 18.2.0.183
- Headless install utPLSQL v3.1.2.2134
- Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
- PL/SQL Release 12.2.0.1.0 - Production

I used this code to run tests:
```
begin
    ut.run('my_package_ut', ut_coverage_html_reporter(), a_include_objects => ut_varchar2_list('my_package'));
end;
/
```
This is what i found out:

1. As long as "working" packages are executed everything works fine. However when a "broken" package is executed the session is broken and i have to disconnect and reconnect in sqldeveloper to get it to work again.

2. There seems to be different behavior when using a completely fresh database. We set up a new empty database and ran some previously broken packages and they were working just fine. But as soon as a full `ut.run()` was executed it didn't seem to work anymore.

3. There is definitely a pattern regarding length. I'm not sure which length but it seems to be the length of a table name or a column name.

To debug this length behavior I took one of our "broken" packages and started removing code until i narrowed it down to one statement:
```
insert into t_attribute_type_translation (value1, value2, value2)
values ('foo', 'bar', 'baz')
returning attribute_type_translation_id into my_local_variable;
```
Without this statement the coverage report works just fine. However with this statement we get the dbms_profiler error.

Could this be related to the change oracle made regarding max length of table and column names in oracle 12.2 (https://oracle-base.com/articles/12c/long-identifiers-12cr2)?

**Comment by jgebal** [comment]
Can you please expand on what do you mean by "broken" package?
Is the package in an invalid state or do you refer to a package as "broken" because it's causing profiler to fail?

Can you simply try the following experiment?
```
begin
  dbms_profiler.start_profiler('test');  
  HERE   execute the code in "broken" pacakge;  
  dbms_profiler.stop_profiler;
end;
/
begin
  dbms_profiler.start_profiler('test'); 
  HERE   execute the test procedure that calls the "broken" package  
  dbms_profiler.stop_profiler;
end;
/
begin
  dbms_profiler.start_profiler('test'); 
  ut.run('the_test_for_broken_package'); 
  dbms_profiler.stop_profiler;
end;
/
```

The error is definitely not related to long names, as the statement you're executing does not contain long names.

Please let me know which of the above 3 examples is throwing exception.

**Comment by SDepn** [comment]
Sorry for not clarifying that. I refer to packages as "broken", because their code throws the profiler exception. The package compiles just fine.

Another thing that i forgot to clarify is that the insert statement breaking the code is part of the `_ut` package, not the main package. This particular code is used in the `%beforeall` procedure.

I tried your code and i did not get it to run at all. Whatever i tried, i always got this error:
```
ORA-06528: Error executing PL/SQL profiler
ORA-06512: at "SYS.DBMS_PROFILER", line 132
ORA-06512: at "SYS.DBMS_PROFILER", line 141
ORA-06512: at line 4
06528. 00000 -  "Error executing PL/SQL profiler"
*Cause:    An error occurred in during execution of a PL/SQL profiler
           procedure.
```
So this code to get the html coverage worked just fine:
```
begin
    ut.run('p_contact_ut', ut_coverage_html_reporter(), a_include_objects => ut_varchar2_list('p_contact'));
end;
/
```

While this one does not work at all.

```
begin
  dbms_profiler.start_profiler('test'); 
  ut.run('p_contact_ut');
  dbms_profiler.stop_profiler;
end;
/
```

**Comment by jgebal** [comment]
So this clearly indicates problem with how you have profiler setup not utPLSQL.
Is DBMS_PROFILER granted to public?
Are all 3 profiler tables and 1 sequence having public synonyms and are granted to public?
Check all profiler requirements and once my examples run fine you should not have any issues anymore.

**Comment by SDepn** [comment]
Thanks this fixed it. I can now execute profiler tests without an issue. I managed to narrow down the issue to some basic import statements.

So this statement works just fine:
```
begin
  dbms_profiler.start_profiler('test'); 
  insert into t_role (descriptor, code, status_ind, public_flag, report_flag)
        values('UT_Role_01', 'UT_ROL01', 'ACT', 'N', 'N');
  dbms_profiler.stop_profiler;
end;
```
This one does not:
```
begin
  dbms_profiler.start_profiler('test');   
  insert into t_attribute_type_translation (attribute_type_id, language_ind, descriptor)
        values (82, 'U1', 'UT_Translation_01');
  dbms_profiler.stop_profiler;
end;
```

So this actually seems to be an error on the oracle side and not on your side.

**Comment by jgebal** [comment]
I'm happy you've got to the bottom of it.

**Comment by SDepn** [comment]
Update:

I found the root cause. In the `plsql_profiler_units` table is a column called `unit_name`. This column is defined as `varchar2(32 byte)`. This is too small for our unit names. Altering this tables and setting it to a length of 128 fixed this problem.
```
ALTER TABLE ut3.plsql_profiler_units modify (unit_name varchar2(128));
```


According to your documentation these tables are created by your scripts. Would you consider updating this?. The unit_name column length should be at least 128 to be the same as the allowed table length. (https://oracle-base.com/articles/12c/long-identifiers-12cr2)

**Comment by ThisGuenter** [comment]
A current version of proftab.sql 12c/18c should be used. plsql_profiler_runs.run_owner varchar2(128), plsql_profiler_runs.unit_type/plsql_profiler_runs.unit_owner/plsql_profiler_runs.unit_name varchar2(128) - instead of the current varchar2(32)

**Comment by jgebal** [comment]
Thanks @SDepn , @ThisGuenter - we will include a fix in next release for this.
