### ISSUE TITLE
Annotation REGEXP problem with NLS CANADIAN FRENCH

### ISSUE THREAD

**Issue by caronD** [utPLSQL/utPLSQL#844]
When using ut.run(); using the last release i've got this error : 

>Warnings:
> 
>  1) test_between_string
>      Unsupported annotation "--%test(returns substring from start position to end position)". Annotation ignored.
>      at "FOD.TEST_BETWEEN_STRING.NORMAL_CASE;", line 5

I'm using Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production, my NLS is CANADIAN FRENCH

**Comment by jgebal** [comment]
From our conversation on SLACK.

The issue is related to regexp_substr syntax in `ut_annotation_parser`

We use named-parameter `modifier` which is not part of oracle-documentaion.
We should be using: `match_param` or in fact remove it, as the regexp itself is doing a case-insensitive search.

I've confirmed with @caronD that the issue is resolved after removing the `modifier=>'i'`.

**Need to create a test case to prove and document the bug before fixing it**
