### ISSUE TITLE
Create single entry procedure/function for running tests

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#86]
Currently suite_manager has several ling-named procedures to run ut's.
Can we have just one name as an entry point?

**Comment by Pazus** [comment]
Do you mean a similary named procedures dirrefer by parameter types?

**Comment by jgebal** [comment]
Hi @pazus 
What I was thinking of is to define a consistent, simple and flexible way for developers to execute tests.
Looking at most ut frameworks, they offer single-line or single command ut invocation.

I would like to see something similar in utplsql.
The inputs for a runner should be probably:
- what to run: suite/suites/ut package/ a test under carret in package (for IDE integrations)/a test procedure in package
- what to skip (optionally)
- what should be the report formats (reporters)
- what should be the report outputs
- default transaction control for run
- default null comparison for run
- more??

What we define initially should be created in a way that will be easy to extend.

**Comment by Pazus** [comment]
@Jgebal, now I see your point!

So we should have procedures `run_singlr_suite`, `run_schema_suites` (run test is arguable due to suite setup may be required).

Main parameters. Run_single_suite: `ut_test_suit`e or owner/package name or `suite_path`.
Run_schema_suites: schema name.

Both procedures accept reporter(which contains out-putter) to use and list of tags to include(all of empty)/exclude (none if empty).

I don't think transaction control and null comparison should be configurable on execution. Imagine I have a suite package with several tests and suite setup. If it is designed with rollback after test in mind then all the test assume that the data at its start is the same as after the setup procedure. If I run such suite with overridden transaction control most likely the second and the following tests will behave  
wrong.
The same is true for null comparison. I think this behavior is set on design.

**Comment by Pazus** [comment]
May we leave only the singe entry point passing for this issue as it is crucial to have it before Alfa and postpone passing multiple entry points to another Issue with another milestone?

**Comment by Pazus** [comment]
Single entry point is implemented for a single-path argument, merged by PR #113

**Comment by Pazus** [comment]
Moved the milestone to 3.1. I think multipath implementation won't be done before that.

**Comment by jgebal** [comment]
I think we can consider this task close, despite the fact the multipath runner is not complete. API is there which was the expectation for this task.
