### ISSUE TITLE
Documentation: Mark specific topics/features with "available since <version>"

### ISSUE THREAD

**Issue by pesse** [utPLSQL/utPLSQL#890]
utPLSQL grows rapidly and continues to get new, great features. 
I think it would be very beneficial to have the documentation/userguide state which features are available since which version.

**Comment by pesse** [comment]
Maybe also add some indication of whether and how some features can be utilized with cli and SQLDeveloper plugIn.
@PhilippSalvisberg  @jgebal thoughts?

**Comment by PhilippSalvisberg** [comment]
Not sure, if this is easy to understand. For example, the feature to compare cursors is available in the CLI and the SQLDev extension, but there is no directly related CLI nor SQLDev extension feature. In the CLI it does not make sense. In the SQLDev extension it could, e.g. to support building a test case.

**Comment by pesse** [comment]
Valid point - I thought more about the different run-possibilities. 
I'll try an approach and request your feedback then :)

**Comment by jgebal** [comment]
How about versiom history document?
It's easier to maintain and gives really good visibility into what was changed/added.
I'm worried of polluting main documemt with available since.
utPLSQL has separate documentation publisjed with each version.
Maybe a "what's new in this release" document as part of documentation with links do doc page or issue (for bug fixes)?

**Comment by jgebal** [comment]
I wouldn't put "available since" into main doc
